# Generated by Django 4.1.2 on 2023-01-26 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
